name: Render README

on:
  push:
    branches: [main]

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - uses: r-lib/actions/setup-pandoc@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install rmarkdown
        run: |
          install.packages(c("knitr", "rmarkdown"))
        shell: Rscript {0}

      - name: Render README.Rmd
        run: |
          rmarkdown::render("README.Rmd")
        shell: Rscript {0}

      - name: Commit rendered README.md
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md       
          # Only commit if there are changes
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Render README.md from README.Rmd"
            git push
          fi
