name: Render Quarto README with R

on:
  push:
    branches: [main]

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R packages
        run: |
          install.packages(c("knitr", "rmarkdown"))
        shell: Rscript {0}

      - name: Render README.qmd
        run: |
          quarto render README.qmd

      - name: Commit rendered README.md
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Render README.md from README.qmd" || echo "No changes to commit"
          git push
          