name: Sync lib folder

on:
  push:
    branches: ['main']
    paths: ['lib/**']

jobs:
  sync-repos:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout source repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        path: source-repo
    
    - name: Checkout target repository: charts-lib
      uses: actions/checkout@v4
      with:
        repository: ONSvisual/charts-lib
        token: ${{ secrets.SYNC_LIB }}
        fetch-depth: 0
        path: charts-lib

    - name: Checkout target repository: otherCharts
      uses: actions/checkout@v4
      with:
        repository: ONSvisual/otherCharts
        token: ${{ secrets.SYNC_LIB }}
        fetch-depth: 0
        path: otherCharts
    
    - name: Replace lib folder in charts-lib
      run: |
        rm -rf charts-lib/lib
        mkdir -p charts-lib/lib
        rsync -av --exclude='.git' --exclude='.github' source-repo/lib/ charts-lib/lib/

    - name: Replace lib folder in otherCharts
      run: |
        rm -rf otherCharts/lib
        mkdir -p otherCharts/lib
        rsync -av --exclude='.git' --exclude='.github' source-repo/lib/ otherCharts/lib/
    
    - name: Commit and push changes to charts-lib
      run: |
        cd charts-lib
        git config user.email "action@github.com"
        git config user.name "GitHub Action"
        
        git add lib/
        if git diff --staged --quiet; then
          echo "No changes to commit in charts-lib"
        else
          git commit -m "Sync lib from source: ${{ github.sha }}"
          git push
        fi

    - name: Commit and push changes to otherCharts
      run: |
        cd otherCharts
        git config user.email "action@github.com"
        git config user.name "GitHub Action"
        
        git add lib/
        if git diff --staged --quiet; then
          echo "No changes to commit in otherCharts"
        else
          git commit -m "Sync lib from source: ${{ github.sha }}"
          git push
        fi
